language: node_js
node_js:
- 8.4.0
install:
- npm install -g mocha browserify
script:
- npm run test
after_success:
- npm run browserify
- ls
deploy:
- provider: npm
  email: greg@trofix.co
  api_key:
    secure: t2aQto3XwplazAdtpjki/MGZGrvzWgGVJ+mjd9Apjq6MSHFSI1Yncgg36nPQNhZRB49DuobMvKUmkkhUWO6Dtva2pBEb4CGIz+39c//8jV9GjXoerV5vp+ywCdvzB3h1Al9Fvit91vMs1uVvgzcyROLRFPBNNAe/BKx3zeL2l48OvWla6kifotgqE25iwawuvw3XCxR7zUtJNYlHjMkeBK91eqsZ+GOTNTkK/aqleKfKvjp4ImcmfITKJy8WR6doFRkn6FjWQfUo0zApB7GfoIx5fqAUgI7gUMxfvP10ZXXreMd/vvTm3my0SHycL5y26zNXxg7KOdJ1+sPnC95azkiNfa1B5elOcl0QH+0MeDNB6g8Wg0H7R3DSZ/yC0CSN/DOSgKU5IUxhEZtTMvA0c/Ccqt0Sj3A406IMGrtxxJRIBCAAS2wztVu4Lpa26gIc1x3QkvpHHoMu12CFHhdUovX4g6IsysRX0FVU8wF7KzIrPM7vwDdbZJhulY0DRD5BFC97DApGrmcVZKQSd/BMo+hyFKHLmxmujRrbZ971b63dzyIzwhiQW9mdHv1/39hxVxtM8Inl23GuMqpnzSa66/Y36KxSr2Gsfb2LdqVAmcAK7znaSFDukQ5AGPD5JzRaiDN3dARZ62BO27fWJmaT0fPBDgQ43N1BFwFudIBQtvM=
  on:
    tags: true
    repo: moriczgergo/btwn
- provider: releases
  api_key:
    secure: GKbkw+KUzXf5pqhDXlApJHsiOPkV0xVr3PxswIn6izSJ0ONMRmgtFj3xznnuGWvjRqwH50yQuwKgVir3LMG4FEHFx1LEG1s6Yv2p/oR6T/UUm+7H9OB/+nKSJw1QFxvA8wxRNM+NQpMKbekXS1PZYcFufiXKj0Q0jfYOv9xXcxUYe2SflXGLanmda2nzCwB8rJ0utN7KK2CixouI6Ik3T2wEKwzj2D8ZjBCChhu8reMKmDGHsfFxCIberIjM3C3/h+5JHewdImuKkLAiVsbcFmXXqPkfxRvYc+dgHNpWwgH6r/unHKzgZuecMZLJ0kiIUmFESTHpKOYHn7+HvG6WMG5JILGzHAy7eU/811IFQPRSdzH/zcOWRUF75tdwlqwF5upFP6kNzsfdCPCbwL44tSY0P76iDB2cXRMlAstK4CfTmSvwpGr8Nj3ZGyu2dT2IAJ1a3oz0x6Zrm+gG4voN3rcpBJJ/NCUxWSbFpaV7CFcSFHthr6lbqySUKMJ9OgJX+/tmtB12X1EjPFWgtw9dRf7L3ee4t0YkwIW0wQfdHqDyVKyA2HnYN9nXZ5ZMGSmfZRq6BOaXzl57ngbsHsp7xkZWuIfhbHJlFKtuNI6JZ7R9qEX4Q/mJ7RCgv9VSMb8nYBj4pdcMYFy1SbdLEJ3y1q7eimG8gzF4RclJz/YMqxM=
  file: $TRAVIS_BUILD_DIR/btwn.js
  on:
    tags: true
    repo: moriczgergo/btwn